---
- name: Updating language pack
  apt: pkg={{system_locale_language_pack}}
  tags: locale

- name: Updating locale
  command: /usr/sbin/update-locale LANG={{system_locale_lang}} LC_ALL={{system_locale_lang}}
  tags: locale
